### ISSUE TITLE
Invalid float values parsed from .toml file on Linux

### ISSUE THREAD

**Issue by aborisovich** [marzer/tomlplusplus#179] opened 2022-11-26 19:52 UTC
## Environment
**toml++ version and/or commit hash:**  GIT_TAG v3.2.0

**Compiler:**   g++ (Debian 10.2.1-6) 10.2.1 20210110

**C++ standard mode:** C++17

**Target arch:**  x64

**Library configuration overrides:**  TOML_HEADER_ONLY

**Relevant compilation flags:**  No. 
[compile_commands.json.log](https://github.com/marzer/tomlplusplus/files/10096926/compile_commands.json.log)

## Describe the bug
Float variables have wrong value after parsing from .toml file 
[formatted_data.toml.txt](https://github.com/marzer/tomlplusplus/files/10096929/formatted_data.toml.txt) (Changed extension to .txt to upload to Github).

Values retrieved using ostringstream << operator on toml::table.
[LastTest.log](https://github.com/marzer/tomlplusplus/files/10096927/LastTest.log)
Retrieved values:
positiveFloat1 = 0.84821299999999999
positiveFloat2 = 6.9341999999999997
negativeFloat = -995.92139999999995
(all float values are wrong).
Moreover, positiveFloat1 is listed twice!

## Steps to reproduce (or a small repro code sample)
```
fs::path pathTested = GetParam();

fwsign::TomlReader tomlReader;
std::optional<toml::table> result = tomlReader.tomlFileRead(pathTested);

if(!fs::exists(pathTested) && !fs::exists(fixture.fwsignConfigDir / pathTested))
{
    ASSERT_FALSE(result.has_value());
    return;
}

if(!fs::is_regular_file(pathTested) && !fs::is_regular_file(fixture.fwsignConfigDir / pathTested))
{
    ASSERT_FALSE(result.has_value());
    return;
}

if(pathTested.extension() != ".toml")
{
    ASSERT_FALSE(result.has_value());
    return;
}

std::ostringstream temp;
temp << result.value();
std::string stringResult = temp.str();

// toml content after parsing is unordered - check for substrings
for(auto& entry : fixture.tomlTypesData.matchingFormatText)
{
    ASSERT_TRUE(stringResult.find(entry) != std::string::npos) <<
        "Did not find:\n" << entry << "\nin:\n" << stringResult << std::endl;
}

```

## Additional information
Same code, bug is not reproduced on Windows 11 (compiled with MSVC 19.34.31933.0).
See: https://github.com/Andrey-Borisovich-Quality-Technologies/fw-sign/pull/14
Checks: https://github.com/Andrey-Borisovich-Quality-Technologies/fw-sign/actions/runs/3555112328/jobs/5971618751
And passing Windows build: https://github.com/Andrey-Borisovich-Quality-Technologies/fw-sign/actions/runs/3555112328/jobs/5971622441

**Comment by marzer** [comment] 2022-11-26 20:15
This isn't a bug in toml++ but in the underlying float parsing implementation used by the version of the standard library you're compiling against. The reason it works correctly on windows is because the MSVC STL has `std::from_chars` for floating-points, whereas libstdc++ and libc++ either lack floating-point `std::from_chars` or it's broken, so there I fall back to a stringstream-based implementation.

You can try to force use of `std::from_chars` using `#define TOML_FLOAT_CHARCONV 1`, but your mileage may vary.

> Moreover, positiveFloat1 is listed twice!

What? I tested your sample toml and there's no duplication. This isn't correct, or there's something wrong with your tests.

**Comment by marzer** [comment] 2022-11-26 20:44
I just tried your TOML on x64 linux (ubuntu) both locally here on my machine, and remotely on the [github actions](https://github.com/marzer/tomlplusplus/actions/runs/3555302571/jobs/5971916862), and it parses correctly and round-trips the values exactly. I'm going to close this as 'not a bug' since it seems the issue lies somewhere in your standard library locally.

**Closed by marzer** 2022-11-26 20:44 UTC
Labels: bug

**Comment by aborisovich** [comment] 2022-11-27 23:03
Thanks for info, I'll look into it.

**Comment by marzer** [comment] 2022-11-27 23:49
Might be something as simple as floating-point optimization, or similar. Worth noting that the values aren't really 'wrong'; they're floating-point and are out by like 0.000000000001, so I think you ought to even reconsider if this is an actual problem. Expecting exactness from floating-point is always a mistake.

**Comment by marzer** [comment] 2022-11-27 23:52
Also perhaps try the most recent build, instead of v3.2.0? I can't think of anything in particular that might be impacting this, but I have fixed a few small bugs, so who knows?

**Comment by aborisovich** [comment] 2023-01-07 16:51
Resolved the issue.
Turned out that TOML does not parse decimal floating points but only binary matching IEEE-754 specification.
However, this is not the problem. The problem is that this TomlPlusPlus library happily parses decimal floating point values without any error and then displays different values after parsing. This feature seems questionable in my opinion, especially that end user may not expect an exact result.
This subject was already mentioned in the https://github.com/toml-lang/toml/issues/572 .
I've used converted https://www.h-schmidt.net/FloatConverter/IEEE754.html to check the actual values.
I think TomlPlusPlus parser should throw parsing errors when the floating point value is not IEEE-754 compliant.
You can do that by using https://en.cppreference.com/w/cpp/types/numeric_limits/is_iec559 function.
Please consider this feature, current implementation of the library forces end-users to write their own validation of floating point values.
