### ISSUE TITLE
vs2022 cannot be used

### ISSUE THREAD

**Issue by 107295472** [marzer/tomlplusplus#200] opened 2023-05-18 01:47 UTC
__declspec(dllimport) public: class std::basic_streambuf<char,struct std::char_traits<char> > * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::pubsetbuf(char *,__int64)" 

## Environment
**toml++ version and/or commit hash:**  
new

**Compiler:**  
    msvc143

**C++ standard mode:**  
    c++ 17

**Target arch:**  
    x64

## Steps to reproduce (or a small repro code sample)
#define GLOG_NO_ABBREVIATED_SEVERITIES 
#include <WinSock2.h>
#include <Windows.h>
#include <gflags/gflags.h>
#include <glog/logging.h>
#include <tchar.h>
#include "string"
#include <string.h>
#include <io.h> 
#include <chrono>
#include "include/Parameter.h"
#include "include/PaddleOCR.h"
#include<opencv2/opencv.hpp>
#include "resultjson.cpp"
#define WRITE_LOG(s) (LOG(INFO)<<s)
#include <ws2ipdef.h>
#include <drogon/drogon.h>
#include <iostream>
#include <include/toml++/toml.h>
#include <codecvt>
#include <urlmon.h>
#include <stdlib.h>
#include <direct.h>
#pragma comment(lib,"urlmon.lib")
int main(int argc, char* argv[])
{  
	const auto data = toml::parse_file("config.toml");
}

**Comment by marzer** [comment] 2023-05-18 07:39
What? I use VS2022 with TOML++ literally every day. Can you post an error message, and maybe the specific VS version you are using.

**Comment by marzer** [comment] 2023-05-18 07:41
Also please note the TOML++ version or commit hash, as required by the issue template. The word "new" is neither of those things.

**Comment by marzer** [comment] 2023-05-18 08:10
I've just tested `examples/simple_parser` in the latest release version of VS2022 (17.6) _and_ the latest preview (17.7), and both compile it without issue. I'm going to treat this as user-error and close it as not a bug. I'll re-consider it if you can provide me with some more (and better) information.

**Closed by marzer** 2023-05-18 08:10 UTC
Labels: bug

**Comment by 107295472** [comment] 2023-05-18 08:49
tomlplusplus-3.3.0,  vs2022 17.3.4

**Comment by marzer** [comment] 2023-05-18 08:53
I also asked for a compiler error message. I can't help you if you don't give me good information. You've given me basically nothing to work with.

**Comment by 107295472** [comment] 2023-05-18 09:05
cannot resolve symbol    __declspec(dllimport) public: class std::basic_streambuf<char,struct std::char_traits > * __cdecl std::basic_streambuf<char,struct std::char_traits >::pubsetbuf(char *,__int64)"
![image](https://github.com/marzer/tomlplusplus/assets/6436116/adcebfb3-6ecb-418e-9651-c8d1f87117e4)

**Comment by 107295472** [comment] 2023-05-18 09:06
![image](https://github.com/marzer/tomlplusplus/assets/6436116/d558810b-8795-4283-b097-e1063887ffe5)

**Comment by 107295472** [comment] 2023-05-18 09:07
![image](https://github.com/marzer/tomlplusplus/assets/6436116/640613c0-a7b5-4098-934f-ddff81e8847e)

**Comment by 107295472** [comment] 2023-05-18 09:09
no .lib files

**Comment by marzer** [comment] 2023-05-18 09:12
That symbol is a from your C++ standard library, not from toml++. This is almost certainly a problem with your project configuation - you have a mix of C and C++ headers, which is already a huge red flag, so who knows what else is going on. 

IF you genuinely believe this is an issue with toml++, then first try compiling `examples/simple_parser.cpp` - if you get the same issue there, then sure, it's an issue with my library, but you need to rule it out with a known working sample first.

Also, in future: **paste text, not screenshots**. Screenshots are not searchable, you can't copy and paste from them, et cetera.

**Comment by 107295472** [comment] 2023-05-18 09:17
I don't know c++, now I can't tell which is the c header and the c++ header

**Comment by marzer** [comment] 2023-05-18 09:18
> I don't know c++

Then I can't help you. You shouldn't be making bug reports for libraries written in languages you don't know.
