### ISSUE TITLE
error: undefined symbol: toml::abi_parse_ex::parse(

### ISSUE THREAD

**Issue by theophrastus** [marzer/tomlplusplus#27] opened 2020-05-03 20:31 UTC
This toml++ HEAD from yesterday.  I am very new to toml++ so likely this is my mistake somewhere.  I have been building with the same configuration a long time previously without  toml++.

## Environment
Clang 10 -c++17, 2a

**Target arch (e.g. x64):**  
x64

**Exceptions enabled:**  
Yes, by default

**Relevant `toml++` configuration customizations:**  
hpp:
 #define TOML_ALL_INLINE 0
#define TOML_API __attribute__ ((visibility("default")))
#include <toml.hpp>

cpp:
#include <header-that-includes-toml.hpp>
#define TOML_IMPLEMENTATION
#include <toml.hpp>

**Relevant compilation flags:**

The visibility options are included with:
  
   clang++10 -Icore/nail/9f7356c@@nail@sha -Icore/nail -I../core/nail -Icore -I../core -I../subprojects/optionparser/include -I../subprojects/pcg/include -I../subprojects/tomlplusplus/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -fstack-protector -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -MD -MQ 'core/nail/9f7356c@@nail@sha/config_manager.cpp.o' -MF 'core/nail/9f7356c@@nail@sha/config_manager.cpp.o.d' -o 'core/nail/9f7356c@@nail@sha/config_manager.cpp.o' -c ../core/nail/config/manager.cpp

## Describe the bug

I'm not getting any toml:: symbols at all from the cpp file:

nm -C config_manager.cpp.o | grep toml
0000000000000000 W nail::config::manager_impl::register_toml_handler(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (toml::node*)>)
                 U nail::config::toml_processor::make(nail::config::command_line_processor&)

That's my own symbol.  And linking the shared lib from the file produces:
error: undefined symbol: toml::abi_parse_ex::parse([string_view, string_view])

And then goes on to complain about a missing key function but I guess that would toml::parse().

Apparently there's an interaction with inlines/visibility that I don't understand.

**Comment by marzer** [comment] 2020-05-04 10:01
Ah, by the looks of it you're defining `TOML_IMPLEMENTATION` too late. It should be defined before anything that includes toml.hpp (even transitively). See the example in the docs [here](https://marzer.github.io/tomlplusplus/#mainpage-example-speed-up-compilation).

**Comment by marzer** [comment] 2020-05-05 09:46
@theophrastus since this is functionality already known to work (it's included in the test suite) ill close it as 'not a bug'. The information above should be sufficient to get it working, though if you have trouble with it let me know and I'll try to help further.

**Closed by marzer** 2020-05-05 09:46 UTC
Labels: not a bug
