### ISSUE TITLE
Error when creating a dotted key with the path of a previously created table

### ISSUE THREAD

**Issue by python36** [marzer/tomlplusplus#113] opened 2021-09-02 06:54 UTC
## Environment
**toml++ version and/or commit hash:**
toml++ v2.5.0 037bfdd21f794d7212616d5e6f4f8baab543c472

**Compiler:**  
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**C++ standard mode:**  
17

**Target arch:**  
x86

**Library configuration overrides:**  

**Relevant compilation flags:**  

## Describe the bug
Error when creating a dotted key with the path of a previously created table

## Steps to reproduce (or a small repro code sample)
This is parsed without error:
```toml
[a.b.c]
  z = 9
[a]
  b.c.t = 9
```
Result:
```sh
terminate called after throwing an instance of 'toml::v2::ex::parse_error'
  what():  Error while parsing key-value pair: cannot redefine existing table as dotted key-value pair
```
Higher nesting level:
```toml
[a.b.c.d]
  z = 9
[a]
  b.c.d.k.t = 8
```
Result:
```sh
terminate called after throwing an instance of 'toml::v2::ex::parse_error'
  what():  Error while parsing key-value pair: cannot redefine existing table as dotted key-value pair
```

## Additional information
For example with tomli (Python):
```python
>>> tomli.loads(""" [a.b.c]
...   z = 9
...   [a]
...   b.c.t = 9""")
{'a': {'b': {'c': {'z': 9, 't': 9}}}}
>>> tomli.loads("""[a.b.c.d]
...   z = 9
...   [a]
...   b.c.d.k.t = 8""")
{'a': {'b': {'c': {'d': {'z': 9, 'k': {'t': 8}}}}}}

```

**Comment by marzer** [comment] 2021-09-02 07:29
The first snippet is working as intended; you can't use dotted keys to add KVPs to a [table] after it has been explicitly named. I believe tomli is incorrect here.

The second snippet... I'm not sure. You're not just adding a simple KVP but sub-tables too. https://toml.io/en/v1.0.0#table is not clear enough here. I'll look into it.

**Comment by python36** [comment] 2021-09-02 08:01
I didn’t find in the description that you cannot use dotted keys to add to table.
There is a statement:
`Since tables cannot be defined more than once`
But:
`Dotted keys create and define a table for each key part before the last one, provided that such tables were not previously created.`
That is, when a key is used, the key points to which table, but does not recreate it.

**Comment by marzer** [comment] 2021-09-02 08:35
From the section on dotted keys:

![image](https://user-images.githubusercontent.com/3958019/131809584-ce551e1a-1f8b-472e-b10e-03648879953e.png)

What you're doing in the first example isn't just creating sub-tables, but creating a new value, too. Explicitly naming a table in square brackets is 'defining it', and renders it 'immutable' for the purposes of adding values. It's not a particularly clear part of the spec, but you can read this for more information: [](https://github.com/toml-lang/toml/issues/769)

Adding additional nesting is where it's less clear (your second example), since TOML allows for a bit of mixing here. I believe it should be legal, so I'll review this part of the parser when I get time.

**Comment by marzer** [comment] 2021-09-02 09:22
Actually, you know what? I've just been re-reading various discussions on the topic and now I'm not sure about either point.

**Comment by hukkin** [comment] 2021-09-02 10:55
My interpretation is that 
- only __*inline*__ tables (and arrays) are truly rendered immutable after defining them. Normal tables and AoT arrays are more or less mutable. Simple example that is valid:
  ```toml
  [fruit]

  [fruit.apple]
  ```
  If the table `[fruit]` was truly immutable after "defining" it, I would not be able to change it by adding a subtable.
- Since there are loads of ways to mutate tables after they've been "defined", my interpretation of invalid "redefinition" is something that can potentially overwrite already assigned values:
  ```toml
  [a.b.c] 
  z = 9 

  [a] 
  b.c.t = 9 
  # b.c = 9     # INVALID: Direct reference to explicitly defined a.b.c
  # b.c.z = 9   # INVALID: Direct reference to explicitly defined a.b.c.z
  ```

Quite conveniently my interpretation is in line with how Tomli parses :smile: I do think the spec could use an extra example or two here.

**Comment by marzer** [comment] 2021-09-02 11:21
@hukkin 

> If the table [fruit] was truly immutable after "defining" it, I would not be able to change it by adding a subtable.

My understanding of this only applies to _values_, not sub-tables. Weird either way, and you're definitely right to suggest that the spec needs some extra examples to clarify.

**Comment by hukkin** [comment] 2021-09-02 11:32
> My understanding of this only applies to values, not sub-tables.

Yeah agree with this idea. However, I think terminology may be simpler if the word "immutable" is reserved for the true immutability that applies to inline collections.

Should be noted that neither of the examples in the original post violate the looser concept of "value-immutability" or whatever we should call it.

**Comment by marzer** [comment] 2021-09-04 11:39
Ok so I'm not really any closer to a decision here. I'm leaning towards the first snippet being illegal, and the second one being legal, but the spec is ambiguous enough that I'm not going to make any changes just yet. I've opened up an issue on the TOML repo for further discussion: https://github.com/toml-lang/toml/issues/846

**Comment by marzer** [comment] 2021-09-06 06:45
Ok so the discussion over on the TOML repo seems to confirm pretty firmly that both of these snippets are in fact illegal after all, so I'm going to close this as 'not a bug'. Thanks for bringing it up, though! It highlighted a part of the TOML spec that needed some clarifying.

**Closed by marzer** 2021-09-06 06:45 UTC
Labels: bug, TOML spec

**Comment by python36** [comment] 2021-09-06 08:38
@marzer  Thank you for your time.
