### ISSUE TITLE
Is the "multiple_headers" Conan option working?

### ISSUE THREAD

**Issue by thierryseegers** [marzer/tomlplusplus#86] opened 2021-02-16 00:18 UTC
## Environment
**toml++ version and/or commit hash:2.3.0**  

**Compiler:AppleClang 12**  

**C++ standard mode (e.g. 17, 20, 'latest'):17**  

**Target arch (e.g. x64):x64**  

**Library configuration overrides:**  

**Relevant compilation flags:**  

## Describe the bug

I may about to be a waste of your time but I'm at a loss. I'm trying to get toml++ through Conan and I wanted to have to separate smaller headers rather than the amalgamated header. Because I'm using Conan, I used the `multiple_headers` options set to `True` but it seems I only ever got the single header file.

I'm still a beginner with Conan so it's probably something stupid I'm doing incorrectly but I don't know what. I've tried a couple different things already, all leading to the same outcome. I've made sure to do `conan remove tomlplusplus` between every attempt to make sure I'm "starting fresh"...

## Steps to reproduce (or a small repro code sample)

Because I'm also using CMake, I first tried to include `toml++` like so:

```
conan_cmake_run(REQUIRES
                    tomlplusplus/2.3.0
                OPTIONS
                    tomlplusplus:multiple_headers=True
                BUILD missing
                BASIC_SETUP)
```

but that didn't appear to work. I ended up with just the single file `~/.conan/data/tomlplusplus/2.3.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/toml.hpp`. I also tried `conan install .` from the command line with both a `conanfile.txt` and a `conanfile.py` but neither had the desired effect.

Here's the `conanfile.txt` I tried:
```
[requires]
tomlplusplus/2.3.0

[options]
tomlplusplus:multiple_headers=True
```

and the `conanfile.py` I tried:
```
from conans import ConanFile, CMake

class TomlPlusPlusConan(ConanFile):
   settings = "os", "compiler", "build_type", "arch"
   requires = "tomlplusplus/2.3.0"
   generators = "cmake"
   default_options = {"tomlplusplus:multiple_headers": True}
```

## Additional information

Regardless of the mechanism through which Conan is triggered, I always end up with a `conaninfo.txt` file that looks like this:

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=apple-clang
    compiler.libcxx=libc++
    compiler.version=10.0
    os=Macos

[requires]
    tomlplusplus/2.Y.Z

[options]

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=apple-clang
    compiler.libcxx=libc++
    compiler.version=10.0
    os=Macos

[full_requires]
    tomlplusplus/2.3.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

[full_options]
    tomlplusplus:multiple_headers=True

[recipe_hash]

[env]
```

and I always end up with a single file `toml.hpp` in the folder `~/.conan/data/tomlplusplus/2.3.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include`.

Again, it's probably something stupid on my part due to my inexperience with Conan but after a couple of hours fiddling with this, filing an issue is the best I could think of...

**Comment by marzer** [comment] 2021-02-16 06:49
Well to be honest I lack the conan experience to answer this myself; conan support was added by a pull request from a contributor. (cc: @prince-chrismc)

> I wanted to have to separate smaller headers rather than the amalgamated header.

In the short term it's probably worth me pointing out that there's no difference; with separate headers you include `toml/toml.h`, which is the header that's run through a preprocessor to generate `toml.hpp`; the amount of code you're adding to your project is the same either way. The library is not structured in a way that benefits from breaking it down more than that.

**Comment by prince-chrismc** [comment] 2021-02-16 14:14
I double check and get back to you 👍 

All the conan settings/options look good might be the recipe

**Comment by marzer** [comment] 2021-02-16 14:35
Thanks @prince-chrismc, much appreciated

**Comment by prince-chrismc** [comment] 2021-02-18 00:02
@thierryseegers I was able to copy your `conanfile.py` settings and they are certainly good.

Can you try running the following and sharing the output?

```sh
$ conan install tomlplusplus/2.3.0@  -o multiple_headers=True -b
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
multiple_headers=True
[build_requires]
[env]

tomlplusplus/2.3.0: Forced build from source
Installing package: tomlplusplus/2.3.0
Requirements
    tomlplusplus/2.3.0 from 'conan-center' - Cache
Packages
    tomlplusplus/2.3.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build

Installing (downloading, building) binaries...
tomlplusplus/2.3.0: Configuring sources in /home/cmcarthur/.conan/data/tomlplusplus/2.3.0/_/_/source
Downloading v2.3.0.tar.gz completed [924.93k]

tomlplusplus/2.3.0: Building your package in /home/cmcarthur/.conan/data/tomlplusplus/2.3.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
tomlplusplus/2.3.0: Generator txt created conanbuildinfo.txt
tomlplusplus/2.3.0: Calling build()
tomlplusplus/2.3.0: WARN: This conanfile has no build step
tomlplusplus/2.3.0: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
tomlplusplus/2.3.0: Build folder /home/cmcarthur/.conan/data/tomlplusplus/2.3.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
tomlplusplus/2.3.0: Generated conaninfo.txt
tomlplusplus/2.3.0: Generated conanbuildinfo.txt
tomlplusplus/2.3.0: Generating the package
tomlplusplus/2.3.0: Package folder /home/cmcarthur/.conan/data/tomlplusplus/2.3.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
tomlplusplus/2.3.0: Calling package()
tomlplusplus/2.3.0 package(): Packaged 18 '.h' files
tomlplusplus/2.3.0 package(): Packaged 1 file: LICENSE
tomlplusplus/2.3.0: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
tomlplusplus/2.3.0: Created package revision d84573f95e605661b164ae3d42d81012

$ ls /home/cmcarthur/.conan/data/tomlplusplus/2.3.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
toml.h         toml_date_time.h          toml_json_formatter.h  toml_parse_error.h   toml_print_to_stream.h  toml_utf8_streams.h
toml_array.h   toml_default_formatter.h  toml_node.h            toml_parser.h        toml_table.h            toml_value.h
toml_common.h  toml_formatter.h          toml_node_view.h       toml_preprocessor.h  toml_utf8.h             toml_version.h
```

**Comment by thierryseegers** [comment] 2021-02-18 14:44
@prince-chrismc Thanks for looking into this. I tried your suggestion and it worked for me. (It worked verbatim even though I tried it on a Mac and the configuration is for Linux since this package is just header files anyway).

I experimented a bit more and I observed that the `[options]` line in the configuration appeared to be irrelevant. All that mattered for it to work was the option `-o multiple_headers=True` at the command line. If that is missing, it won't work and I invariably end up with the single header file.

Shown here is the outcome of two attempts. Using `-o` at the command line and no `[options]`:

```
conan install tomlplusplus/2.3.0@  -o multiple_headers=True -b
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

Produced this output:

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
multiple_headers=True
[build_requires]
[env]

// ...

tomlplusplus/2.3.0: Calling package()
tomlplusplus/2.3.0 package(): Packaged 1 file: LICENSE
tomlplusplus/2.3.0 package(): Packaged 18 '.h' files
tomlplusplus/2.3.0: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
tomlplusplus/2.3.0: Created package revision ff1a85abd3aa7b3592a7112f307d7c47
```

And not using `-o` at the command line but specifying `[options]`:

```
conan install tomlplusplus/2.3.0@ -b
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
multiple_headers=True    // "tomlplusplus:multiple_headers=True" doesn't appear to help.
[build_requires]
[env]
``` 
Produced this output:
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

// ...

tomlplusplus/2.3.0: Calling package()
tomlplusplus/2.3.0 package(): Packaged 1 file: LICENSE
tomlplusplus/2.3.0 package(): Packaged 1 '.hpp' file: toml.hpp
tomlplusplus/2.3.0: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
```

**Comment by prince-chrismc** [comment] 2021-02-18 15:37
Yep, so this comes down to the internals of Conan... the current revision of the recipe is marked `header_only` and it deletes __all__ settings and *options*... 
If you notice the `package_id` is the same for both... that's why it was not doing the right thing.

**Comment by marzer** [comment] 2021-02-24 15:42
What's the verdict here @thierryseegers @prince-chrismc? Is this all sorted?

**Comment by thierryseegers** [comment] 2021-02-24 16:03
@marzer I think it is and we can close this.

Incidentally, it opened another problem which may warrant a different issue: I'm working with Visual Studio Code and, apparently, it defines the `__INTELLISENSE__` macro. That, in turn, defines the `TOML_INTELLISENSE` macro in toml_preprocessor.h`. This, in turn, defines the `TOML_HEADER_ONLY` macro which, in turn, defines the `TOML_IMPLEMENTATION` macro.

That has for effect in `toml.h` to `#include "toml_node.hpp"` and other files which are not present in the package and, thus, fails compilation.

Maybe I'm mistaken and I followed an incorrect "reverse path" of macro definition so maybe it's not because of that macro but, regardless, compilation fails.

**Comment by marzer** [comment] 2021-02-24 16:22
Visual studio code only defines that during intellisense parsing; it will not be defined when the code is fed to the actual compiler. That's why it appears defined in the editor.

**Comment by marzer** [comment] 2021-02-24 16:24
That aside, if you choose the multiple headers option, toml_node.hpp _should_ be included. I think I'm not understanding something here.

**Comment by thierryseegers** [comment] 2021-02-24 16:39
@marzer If that's the case, then those files are missing from the package.

**Comment by marzer** [comment] 2021-02-24 16:42
Does it work if you use the single-header version?

**Comment by thierryseegers** [comment] 2021-02-24 16:48
@marzer Yes.

**Comment by marzer** [comment] 2021-02-24 16:51
Huh. I guess the problem isn't fixed after all. I'm beginning to think supporting both modes via Conan is more trouble than it's worth. There's not really any advantage to doing so...

**Comment by thierryseegers** [comment] 2021-02-24 17:19
@marzer Yes, it's starting to look that way... 🤔

**Comment by prince-chrismc** [comment] 2021-02-25 01:26
So If I follow this correctly... I think there's an expectation that `TOML_HEADER_ONLY ` is defined? 

_EDIT: Reviewing the documentation it's super obvious that it's a yes_

https://github.com/marzer/tomlplusplus/blob/5a9166bce8482431e40c056f91ec0d3a0ad72159/README.md#configuration

Option | Type | Default | Description
-- | -- | -- | --
TOML_HEADER_ONLY | boolean | 1 | Disable this to explicitly control where toml++'s implementation is compiled (e.g. as part of a library).

https://github.com/marzer/tomlplusplus/commit/fd07301baefa08f7b2bdfabf1e71c5e263b94e73#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R118

https://github.com/marzer/tomlplusplus/blame/5a9166bce8482431e40c056f91ec0d3a0ad72159/docs/main_page.dox#L386

All of which was committed on Jul 25, 2020

Sadly I have not looked at this library since I added it in April 2020. https://github.com/conan-io/conan-center-index/commits/master/recipes/tomlplusplus/all/conanfile.py 

It should be easy enough to add that one macro for `>=2.1.0`

**Comment by marzer** [comment] 2021-02-25 11:33
Yeah, originally it was `TOML_ALL_INLINE`, but I renames it because that wasn't as clear. Internally the code still checks for that one too for the sake of backwards compatibility, it's not listed in the README.

**Comment by thierryseegers** [comment] 2021-02-25 13:36
I don't want to be more trouble but can I make the following suggestion : that the folder `toml++` is copied to the installation folder, not just its contents ? Users would then do `#include <toml++/toml.hpp>`. I believe it is more typical to have "one folder above" for third-party libraries.

Again, just a suggestion. I don't want to open another can of worms... 😄

**Comment by marzer** [comment] 2021-02-25 13:51
@thierryseegers The 'one folder above' include style is already the case for the multi-header version, so should be the case for the conan install too (I hope). The single-header version deliberately doesn't do that since the typical use-case for a single-header library is that users drop it in their own repo wherever they like, rather than needing to futz with include paths and build tools (ironically).

**Comment by prince-chrismc** [comment] 2021-03-02 00:12
> 1. conan does _not_ interfere with `TOML_HEADER_ONLY`

Yes




> 2\. If the user chooses multi-header mode, conan copies them to `include/toml++/<files>`

No, it's in the wrong directory

```sh
$ ls /home/cmcarthur/.conan/data/tomlplusplus/2.3.0/_/_/package/4b35f355477100272b318e975dacda34e6a73843/include/
toml.h         toml_date_time.h          toml_json_formatter.h  toml_parse_error.h   toml_print_to_stream.h  toml_utf8_streams.h
toml_array.h   toml_default_formatter.h  toml_node.h            toml_parser.h        toml_table.h            toml_value.h
toml_common.h  toml_formatter.h          toml_node_view.h       toml_preprocessor.h  toml_utf8.h             toml_version.h
```




> 3\. If the user chooses single-header mode, conan copies it to `include/toml.hpp`

Yes.

**Comment by prince-chrismc** [comment] 2021-03-02 00:37
New PR 🤞 Third time's the charm!

**Comment by marzer** [comment] 2021-03-02 10:08
Excellent, thanks for following up on this @prince-chrismc!

**Comment by prince-chrismc** [comment] 2021-03-06 20:01
Minus my bad English for the title it was merged.

So it should now have all files for both modes making it easier. I also added it to the test package to compile both. 

I think I got it this time.

**Comment by marzer** [comment] 2021-03-06 20:09
Fantastic, thanks @prince-chrismc! 

@thierryseegers mind giving this a try?

**Comment by thierryseegers** [comment] 2021-03-07 17:13
@marzer Gets a ✅ from my side !

**Closed** 2021-03-07 18:45 UTC
Labels: bug
