### ISSUE TITLE
GCC reports "potential null pointer dereference" in toml_formatter::print

### ISSUE THREAD

**Issue by zaporozhets** [marzer/tomlplusplus#164] opened 2022-07-18 22:50 UTC
## Environment
**toml++ version and/or commit hash:**  
v3.1.0, single-header

**Compiler:**
GCC 11.1.0

**C++ standard mode:**  
20

**Target arch:**  
x64, ARM

**Library configuration overrides:**  
```
In headers
  #define TOML_HEADER_ONLY 0
  #include <toml.hpp>
In source files
  #define TOML_IMPLEMENTATION
  #include <toml.hpp>
```

**Relevant compilation flags:**  
```
-O3 -DNDEBUG -Wall -Werror -Wextra -pedantic -Wno-error=attributes -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wno-error=double-promotion -Wduplicated-branches -Wduplicated-cond -Wextra-semi -Wfloat-equal -Wformat=2 -Wimplicit-fallthrough=5 -Wlogical-op -Wnon-virtual-dtor -Wnull-dereference -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wsign-conversion -Wstrict-null-sentinel -Wsuggest-final-methods -Wsuggest-final-types -Wsuggest-override -Wundef
```

## Describe the bug

In release mode GCC reports the following:
```
/home/taras/yo/build-hmmmm-Desktop_Qt_6_2_0_GCC_64bit-Release/dependencies/tomlpp-src/toml.hpp: In member function ‘void toml::v3::toml_formatter::print(const toml::v3::table&)’:
/home/taras/yo/build-hmmmm-Desktop_Qt_6_2_0_GCC_64bit-Release/dependencies/tomlpp-src/toml.hpp:6737:11: error: potential null pointer dereference [-Werror=null-dereference]
 6737 |    return inline_;
      |           ^~~~~~~
/home/taras/yo/build-hmmmm-Desktop_Qt_6_2_0_GCC_64bit-Release/dependencies/tomlpp-src/toml.hpp:6737:11: error: potential null pointer dereference [-Werror=null-dereference]
/home/taras/yo/build-hmmmm-Desktop_Qt_6_2_0_GCC_64bit-Release/dependencies/tomlpp-src/toml.hpp:6737:11: error: potential null pointer dereference [-Werror=null-dereference]
 6737 |    return inline_;
      |           ^~~~~~~
/home/taras/yo/build-hmmmm-Desktop_Qt_6_2_0_GCC_64bit-Release/dependencies/tomlpp-src/toml.hpp:6737:11: error: potential null pointer dereference [-Werror=null-dereference]
/home/taras/yo/build-hmmmm-Desktop_Qt_6_2_0_GCC_64bit-Release/dependencies/tomlpp-src/toml.hpp:6737:11: error: potential null pointer dereference [-Werror=null-dereference]
 6737 |    return inline_;
      |           ^~~~~~~
/home/taras/yo/build-hmmmm-Desktop_Qt_6_2_0_GCC_64bit-Release/dependencies/tomlpp-src/toml.hpp:6737:11: error: potential null pointer dereference [-Werror=null-dereference]
cc1plus: all warnings being treated as errors

```

## Additional information
    Please let me know if you need any additional pieces of context, code, etc.

**Comment by marzer** [comment] 2022-07-19 06:43
Thanks for the report. Seems like a weird one- the code in the warning isn't doing any explicit pointer derefencing so I guess it's talking about the `this` pointer of the table object. Are you calling `table::inline()` anywhere yourself, or was this warning generated from somewhere inside the library?

**Comment by marzer** [comment] 2022-07-29 09:09
@zaporozhets ?? Can you answer my question above, to provide some more context? I haven't been able to reproduce this, and without more information about how you triggered this, I'll just close it as not-a-bug.

**Comment by marzer** [comment] 2022-07-31 15:50
Welp, since I can't reproduce this I'll go ahead and close this. Feel free to re-open it if you can come back with some more information :)

**Comment by zaporozhets** [comment] 2022-08-07 11:17
@marzer sorry for the late reply. This issue happens only in release mode and with "-Wnull-dereference" flag. I have attached a project with src/cmake to reproduce it.

I'm not 100% sure but for me it seems that GCC complains about code in  `void toml_formatter::print(const table& tbl)`. Because `get_as` can return `nullptr`. So `!arr->template get_as<table>(0u)->is_inline()` potentially can dereference null pointer.
What do you think?
 

```cpp
#include <fstream>
#include <toml.hpp>

int main() {
  toml::table config_;
  config_.insert_or_assign("test_val", "yoyo");

  std::ofstream outdata("yoyo.toml");
  outdata << config_;
  return 0;
}
```

```cmake
cmake_minimum_required(VERSION 3.5)

project(toml-demo LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(FetchContent)
set(FETCHCONTENT_BASE_DIR ${CMAKE_BINARY_DIR}/deps)

FetchContent_Declare(tomlpp
  GIT_REPOSITORY          https://github.com/marzer/tomlplusplus.git
  GIT_TAG                 v3.1.0
  GIT_PROGRESS            ON
  GIT_SHALLOW             ON
  GIT_SUBMODULES          ""
)
FetchContent_GetProperties(tomlpp)
if(NOT tomlpp_POPULATED)
  FetchContent_Populate(tomlpp)
  add_library(tomlpp INTERFACE)
  target_include_directories(tomlpp INTERFACE ${FETCHCONTENT_BASE_DIR}/tomlpp-src/)
endif()

add_executable(toml-demo main.cpp)
target_compile_options(toml-demo PRIVATE
    "-Wall"
    "-Werror"
    "-Wextra"
    "-pedantic"
    "-Wnull-dereference"

)

target_link_libraries(toml-demo tomlpp)

```


```bash
mkdir build
cmake -DCMAKE_BUILD_TYPE=Release  -B build
cmake --build build
```

**Comment by marzer** [comment] 2022-08-07 20:07
Ah, cool, thanks for the follow-up. I'll have a look into this at some point during the week :)

**Comment by marzer** [comment] 2022-08-08 19:59
> Because get_as can return nullptr. So !arr->template get_as<table>(0u)->is_inline() potentially can dereference null pointer.

Yup, this is the cause. It's a false positive though; if `is_array_of_tables()` has returned `true` then then there's no way for `get_as<table>(0)` to return `nullptr`. I've refactored the code to hopefully fill GCC's static analysis here with a bit more confidence, and haven't been able to trigger the warning. Let me know if that works for you. Thanks for the report!

**Closed** 2022-08-08 19:59 UTC
Labels: bug
